/**
 * tmx2js.mjs — converts the original 2019 Tiled maps into a plain JS module.
 *
 * The remaster does not redraw the levels. It reads the exact same .tmx files
 * that Hasan and Bilal built in Tiled in 2019 and bakes them into docs/js/levels.js
 * so the page needs no fetch() and works from file:// as well as from Pages.
 *
 * Two details are carried over from libGDX so the geometry matches the Java game:
 *
 *  1. Tiled writes rows top-down; libGDX's TiledMapTileLayer indexes y bottom-up.
 *     Rows are flipped here so row 0 is the floor, matching GMap.getByCoordinate().
 *
 *  2. libGDX's TiledMapTile.getId() returns the *global* id, which is what
 *     TileType.getTileTypeById() switches on. So gids are kept verbatim as the
 *     gameplay id, and only the drawing index is resolved per tileset. level1.tmx
 *     imports the same tileset three times (firstgid 1, 11, 21), which is why its
 *     door is gid 31 while level2/level3 doors are gid 11 — the duplicate that
 *     forced TileType.DOORD into existence.
 *
 * Usage: node tools/tmx2js.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const mapDir = join(root, 'docs', 'assets', 'maps');

// title / subtitle / spawn come from the Java: entities.json for level 1, and the
// respawn coordinates hard-coded in Entity.update() for levels 2 and 3.
const LEVELS = [
  { file: 'level1.tmx',   name: 'The Yard',      subtitle: 'Get off the ground floor.',       spawn: [40, 90] },
  { file: 'level2.tmx',   name: 'Cell Block B',  subtitle: 'Down is the only way out.',       spawn: [41 * 16, 14 * 16] },
  { file: 'level3.1.tmx', name: 'The Long Drop', subtitle: 'Last door. Then daylight.',       spawn: [37 * 16, 5 * 16] },
];

function attr(tag, name) {
  const m = tag.match(new RegExp(`${name}="([^"]*)"`));
  return m ? m[1] : null;
}

function parse(xml) {
  const mapTag = xml.match(/<map[^>]*>/)[0];
  const width = +attr(mapTag, 'width');
  const height = +attr(mapTag, 'height');

  // Every tileset in this project is the same 16px strip; all we need is the
  // firstgid of each import so a gid can be turned back into a column index.
  const firstgids = [...xml.matchAll(/<tileset[^>]*>/g)]
    .map((m) => +attr(m[0], 'firstgid'))
    .sort((a, b) => a - b);

  const layers = [...xml.matchAll(/<layer[^>]*>[\s\S]*?<\/layer>/g)].map((m) => {
    const csv = m[0].match(/<data encoding="csv">([\s\S]*?)<\/data>/)[1];
    const flat = csv.trim().split(',').map((n) => +n.trim());
    const rows = [];
    for (let r = 0; r < height; r++) rows.push(flat.slice(r * width, (r + 1) * width));
    return rows.reverse(); // top-down (Tiled) -> bottom-up (libGDX)
  });

  return { width, height, firstgids, layers };
}

// gid -> column in newTileSet.png (11 tiles wide, 16x16 each)
function tileIndex(gid, firstgids) {
  if (gid === 0) return -1;
  let base = 1;
  for (const f of firstgids) if (gid >= f) base = f;
  return gid - base;
}

const out = [];
out.push('// GENERATED by tools/tmx2js.mjs from the original 2019 Tiled maps. Do not hand-edit.');
out.push('// Source of truth: docs/assets/maps/*.tmx (untouched since 2019).');
out.push('');
out.push('window.PR = window.PR || {};');
out.push('PR.TILE = 16;');
out.push('PR.LEVELS = [');

for (const meta of LEVELS) {
  const xml = readFileSync(join(mapDir, meta.file), 'utf8');
  const { width, height, firstgids, layers } = parse(xml);

  // Bake the draw index alongside the gid once, so the renderer never has to
  // think about tileset resolution again.
  const draw = layers.map((rows) => rows.map((row) => row.map((g) => tileIndex(g, firstgids))));

  out.push('  {');
  out.push(`    file: ${JSON.stringify(meta.file)},`);
  out.push(`    name: ${JSON.stringify(meta.name)},`);
  out.push(`    subtitle: ${JSON.stringify(meta.subtitle)},`);
  out.push(`    spawn: { x: ${meta.spawn[0]}, y: ${meta.spawn[1]} },`);
  out.push(`    width: ${width},`);
  out.push(`    height: ${height},`);
  out.push('    // gid grids, [layer][row-from-bottom][col]; gid doubles as TileType id');
  out.push('    gids: [');
  for (const rows of layers) out.push(`      [${rows.map((r) => `[${r.join(',')}]`).join(',')}],`);
  out.push('    ],');
  out.push('    // column in newTileSet.png for the same cell, -1 = empty');
  out.push('    draw: [');
  for (const rows of draw) out.push(`      [${rows.map((r) => `[${r.join(',')}]`).join(',')}],`);
  out.push('    ],');
  out.push('  },');
}

out.push('];');
out.push('');

writeFileSync(join(root, 'docs', 'js', 'levels.js'), out.join('\n'));
console.log(`wrote docs/js/levels.js (${LEVELS.length} levels)`);
